version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "8000:8000"
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://64.225.110.85:9000
      NEXT_PUBLIC_BASE_URL: http://64.225.110.85:8000
      NEXT_PUBLIC_DEFAULT_REGION: eu
      REVALIDATE_SECRET: supersecret
